# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --timeout-keep-alive 0 --reload
    volumes:
      - .:/app
    ports:
      - 8008:8000
