# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - "8000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ssl.rule=Host(`dtxns.in`) && Path('/ssl')"
      - "traefik.http.routers.ssl.tls=true"
      - "traefik.http.routers.ssl.tls.certresolver=letsencrypt"

  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/app/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./traefik-public-certificates:/certificates"


volumes:
  traefik-public-certificates:
