"""empty message

Revision ID: 15b6efa11fbd
Revises: acfb1d8fed59
Create Date: 2022-10-20 16:36:41.015416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b6efa11fbd'
down_revision = 'acfb1d8fed59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
