"""empty message

Revision ID: 2f46b32d4ab6
Revises: f763b820ec85
Create Date: 2022-10-20 16:23:08.050295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f46b32d4ab6'
down_revision = 'f763b820ec85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
