"""empty message

Revision ID: b99f4f6957a7
Revises: 1a87681b6274
Create Date: 2022-10-19 16:19:37.904228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99f4f6957a7'
down_revision = '1a87681b6274'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
