"""empty message

Revision ID: f697c16588a6
Revises: 34cdfc69632b
Create Date: 2022-10-20 17:24:05.152524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f697c16588a6'
down_revision = '34cdfc69632b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
