"""empty message

Revision ID: 1a87681b6274
Revises: 66b208d9f91c
Create Date: 2022-10-19 12:16:01.349943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a87681b6274'
down_revision = '66b208d9f91c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'transaction_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('transaction', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('transaction', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction', 'transaction_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
