"""empty message

Revision ID: 34cdfc69632b
Revises: 15b6efa11fbd
Create Date: 2022-10-20 17:22:29.466534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cdfc69632b'
down_revision = '15b6efa11fbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_transaction_id_fkey', 'tag', type_='foreignkey')
    op.drop_column('tag', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tag_transaction_id_fkey', 'tag', 'transaction', ['transaction_id'], ['id'])
    # ### end Alembic commands ###
