"""empty message

Revision ID: 4e9f33f6846f
Revises: b99f4f6957a7
Create Date: 2022-10-20 16:19:10.126735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9f33f6846f'
down_revision = 'b99f4f6957a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
